## Distinct Powers

## How many distinct terms are in the sequence generated by a^b for
## 2 <= a <= 100 and 2 <= b <= 100?


from time import perf_counter
import math
LOWER_LIMIT = 2
UPPER_LIMIT = 100

def solve():
    nums = []
    for a in range(LOWER_LIMIT, UPPER_LIMIT+1):
        for b in range(LOWER_LIMIT, UPPER_LIMIT+1):
            nums.append(math.pow(a, b))

    return len(list(set(nums)))


if __name__ == '__main__':
    start = perf_counter()
    solution = solve()
    end = perf_counter()
    print(solution)
    total = end - start
    print(f'Program takes {total} seconds to complete!')